### ISSUE TITLE
README.md propping up - writing things on it

### ISSUE THREAD

**Issue by 3dkfi** [hacklabmikkeli/Spede-2.0#4]
Document this project for the next generations of Spede 3.0!

**Comment by pragyaasapkota** [comment]
Please specify what you wish to have in your readme or tell me if we want to custom and I will prepare it for you.

**Comment by pragyaasapkota** [comment]
Please assign me

**Comment by pragyaasapkota** [comment]
@3dkfi

**Comment by 3dkfi** [comment]
@Pragya2056 You have been assigned! Make a fork and pull request when you can! :)

**Comment by pragyaasapkota** [comment]
> Please specify what you wish to have in your readme or tell me if we want to custom and I will prepare it for you.

please specify!!

**Comment by pragyaasapkota** [comment]
@3dkfi
